name: pism-ragis
channels:
  - conda-forge
dependencies:
  - black
  - cdo
  - nco
  - ncview
  - petsc
  - petsc4py
  - pre-commit
  - python=3.12.6
  - pylint
  - pytest
  - pip
  - wget
  - pip:
      - -r requirements.txt
