export PISM_PREFIX=$HOME/local/pism
export RAGIS_DIR=/import/c1/ICESHEET/ICESHEET/pism-ragis/
export grid=150
export odir=${RAGIS_DIR}/hindcasts/2025_11_qaamerujup_init_v2

python $RAGIS_DIR/hindcasts/hindcast.py --stress_balance blatter --no-regrid-thickness --start 1900-01-01 --end 1930-01-01 --o_size medium --spatial_ts qaamerujup --boot_file $RAGIS_DIR/data/dem/bedmachine-1931-qaamerujup.nc --exstep monthly  --data_dir $RAGIS_DIR/data  --grid_file $RAGIS_DIR/data/grids/0_Qaamerujup.nc -s chinook-24 -n 24 -q t2small -w 96:00:00 --o_dir $odir -r $grid -e $RAGIS_DIR/uq/ensemble_qaamerujup_ctrl.csv $RAGIS_DIR/calibration/2025_08_grimp_tw/state/g1200m_id_BAYES-MEDIAN_1980-1-1_1984-12-31.nc

python /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/hindcast.py --stress_balance blatter --no-regrid-thickness --start 1900-01-01 --end 1910-01-01 --o_size medium --spatial_ts qaamerujup --boot_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/dem/bedmachine-1931-qaamerujup.nc --exstep monthly --data_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//data --grid_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/grids/0_Qaamerujup.nc -s chinook-24 -n 12 -q t2small -w 96:00:00 --o_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/2026_01_qaamerujup_init -r 128 -e /import/c1/ICESHEET/ICESHEET/pism-ragis//uq/ensemble_qaamerujup_ctrl.csv /import/c1/ICESHEET/ICESHEET/pism-ragis//calibration/2025_08_grimp_tw/state/g1200m_id_BAYES-MEDIAN_1980-1-1_1984-12-31.nc


python /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/hindcast.py --stress_balance blatter --no-regrid-thickness --start 1900-01-01 --end 1910-01-01 --o_size medium --spatial_ts ragis --boot_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/dem/bedmachine-1931-qaamerujup.nc --exstep monthly --data_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//data --grid_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/grids/0_Qaamerujup.nc -s chinook-24 -n 12 -q t2small -w 8:00:00 --o_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/2026_01_qaamerujup_init -r 128 -e /import/c1/ICESHEET/ICESHEET/pism-ragis//uq/ensemble_qaamerujup_ctrl.csv /import/c1/ICESHEET/ICESHEET/pism-ragis//calibration/2025_08_grimp_tw/state/g1200m_id_BAYES-MEDIAN_1980-1-1_1984-12-31.nc



python /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/hindcast.py --stress_balance blatter --no-regrid-thickness --start 1900-01-01 --end 1910-01-01 --o_size medium --spatial_ts ragis  --boot_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/dem/bedmachine-1931-qaamerujup.nc --exstep monthly --data_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//data --grid_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/grids/0_Qaamerujup.nc -s chinook-24 -n 24 -q t2small -w 16:00:00 --o_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/2026_01_qaamerujup_init -r 64 -e /import/c1/ICESHEET/ICESHEET/pism-ragis//uq/ensemble_qaamerujup_ctrl.csv /import/c1/ICESHEET/ICESHEET/pism-ragis//calibration/2025_08_grimp_tw/state/g1200m_id_BAYES-MEDIAN_1980-1-1_1984-12-31.nc


python /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/hindcast.py --stress_balance blatter --no-regrid-thickness --start 1900-01-01 --end 1910-01-01 --o_size medium --spatial_ts qaamerujup  --boot_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/dem/bedmachine-1931-qaamerujup.nc --exstep monthly --data_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//data --grid_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/grids/0_Qaamerujup.nc -s chinook-24 -n 24 -q t2small -w 16:00:00 --o_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/2026_01_qaamerujup_init0 -r 64 -e /import/c1/ICESHEET/ICESHEET/pism-ragis//uq/ensemble_qaamerujup_ctrl.csv /import/c1/ICESHEET/ICESHEET/pism-ragis//calibration/2025_08_grimp_tw/state/g1200m_id_BAYES-MEDIAN_1980-1-1_1984-12-31.nc

python /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/hindcast.py --stress_balance blatter --start 1910-01-01 --end 2010-01-01 --o_size medium --spatial_ts qaamerujup  --boot_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/dem/bedmachine-1931-qaamerujup.nc --exstep monthly --data_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//data --grid_file /import/c1/ICESHEET/ICESHEET/pism-ragis//data/grids/0_Qaamerujup.nc -s chinook-24 -n 24 -q t2small -w 72:00:00 --o_dir /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/2026_01_qaamerujup -r 64 -e /import/c1/ICESHEET/ICESHEET/pism-ragis//uq/ensemble_qaamerujup_ctrl.csv /import/c1/ICESHEET/ICESHEET/pism-ragis//hindcasts/2026_01_qaamerujup_init0/state/g64m_id_PDD-COLD_1900-01-01_1910-01-01.nc

