# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pism-ragis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        miniconda-version: "latest"
        generate-run-shell: true
        environment-file: environment-dev.yml
        auto-activate-base: false
     - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Run tests
      run: |
        python -c "import petsc4py; petsc4py.init(); from petsc4py import PETSc;"
        python -m pytest
