# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pism-ragis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        micromamba-version: "latest"
        generate-run-shell: true
        environment-file: environment.yml
        cache-environment: true
        post-cleanup: 'all'
    - name: Test with pytest
      run: |
        python -m pytest